/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as IndexRouteImport } from './pages/index'
import { Route as ExperiencesInterviewIndexRouteImport } from './pages/experiences-interview/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesInterviewIndexRoute =
  ExperiencesInterviewIndexRouteImport.update({
    id: '/experiences-interview/',
    path: '/experiences-interview/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experiences-interview/': typeof ExperiencesInterviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experiences-interview': typeof ExperiencesInterviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/experiences-interview/': typeof ExperiencesInterviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/experiences-interview/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/experiences-interview'
  id: '__root__' | '/' | '/experiences-interview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperiencesInterviewIndexRoute: typeof ExperiencesInterviewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences-interview/': {
      id: '/experiences-interview/'
      path: '/experiences-interview'
      fullPath: '/experiences-interview/'
      preLoaderRoute: typeof ExperiencesInterviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperiencesInterviewIndexRoute: ExperiencesInterviewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
